name: CraftSlotCommands3
main: com.gmail.bobason01.CraftSlotCommands
version: 2.5
api-version: 1.13
author: crston
commands:
  craftslotcommands:
    description: Admin command for CraftSlotCommands.
    aliases: [csc]
permissions:
  csc.admin:
    description: Access to the CraftSlotCommands command.
    default: op
